### PR TITLE
Proposal fixing test failures and removing the script.

### PR DESCRIPTION
**Pull request by brainbuz**
It was trivial to fix the tests, except for the script test. I started to convert that test  over to Test::Script, but realized it was still going to be a bit of work to complete the migration, and some of the tests might still have to be kept in their old format or abandoned. Given the fact that this module has been failing tests and you haven't gotten complaints, it probably doesn't have high usage. I was looking at it because I was considering writing something that needed to tail a log file, and this Module is perfect for that.

### CODE REVIEW

**Comment by adelton** [comment]
The problem is -- I haven't seen `make test` failing. That's why I've specifically added the tests in GitHub Actions to capture the current behaviour which at least on Fedora and CentOS is sane: https://github.com/adelton/Logfile-Tail/actions/runs/711636786.

So I guess my first question is -- what is the environment where you actually see the test failures? Let's add it to the CI mix first so that we know what we are dealing with, and we don't lose the fix once it's there.

**Comment by brainbuz** [comment]
I'm running on Ubuntu with custom built Perl, I have 5.32 and 5.30 as the system Perl and an install of 5.8 for testing compatibility with ancient Perl. You can always throw out a test release and use  CPAN Testers, reports start coming in a few hours, but it will take a few days to get a good sampling.

**Comment by adelton** [comment]
And you see error (exactly what error) on what version? Because we have CPAN Testers' results at https://cpantesters.org/distro/L/Logfile-Tail.html and the failures are of the type "`rm` does not exist on Windows" or "Can't call method "resource" on an undefined value at /home/cpantesters/perl5/lib/perl5/CPAN/Testers/Web/Controller/Legacy.pm line 249.".

So please let's get a reasonable description of problem (or problems), reproduce them, and fix them while making sure that the tests that we have so far don't regress.

**Comment by adelton** [comment]
We seem to have lost traction here.

**Pull request closed without merging**
